name: unirgb-ir2
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - scikit-learn=1.4.1.post1
  - scipy=1.7.3
  - numpy=1.24.0
  - pillow=8.2.0
  - pip
  - pip:
      - mmcv==2.0.1
